name = "blog-server"
type = "webpack"
account_id = "4c56d734ab8a0f07ce8ebd3cf8404506"
workers_dev = true
route = "riteshpaudel679.com.np/*"
zone_id = ""
compatibility_date = "2024-06-02"

[env.production]
name = "blog"
route = "riteshpaudel679.com.np"