name: CI/CD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 20.x
      uses: actions/setup-node@v2
      with:
        node-version: 20.x
    - name: Install backend dependencies
      run: cd backend && npm ci
    - name: Run backend tests
      run: cd backend && npm test

  frontend:
    needs: backend
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 20.x
      uses: actions/setup-node@v2
      with:
        node-version: 20.x
    - name: Install frontend dependencies
      run: cd frontend && npm ci
    - name: Run frontend tests
      run: cd frontend && npm test
    - name: Build frontend
      run: cd frontend && npm run build
