name: CI/CD

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install server dependencies
        run: cd server && pnpm install
        env:
          PORT: ${{secrets.PORT}}
          MONGO_URL: ${{secrets.MONGO_URL}}
          JWT_TOKEN: ${{secrets.JWT_TOKEN}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: ${{secrets.AWS_REGION}}
          AWS_BUCKET_NAME: ${{secrets.AWS_BUCKET_NAME}}
      - name: Install Netlify CLI
        run: npm install -g netlify-cli
      - name: List client directory contents
        run: ls -l client
      - name: Deploy to Netlify
        run: netlify deploy --dir=server/dist --prod --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --site ${{ secrets.NETLIFY_BE_SITE_ID }}

  client:
    needs: server
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install client dependencies
        run: cd client && pnpm install
      - name: Build client
        run: cd client && pnpm run build
        env:
          VITE_API_URL: ${{secrets.VITE_API_URL}}
      - name: Install Netlify CLI
        run: npm install -g netlify-cli
      - name: List client directory contents
        run: ls -l client
      - name: Deploy to Netlify
        run: netlify deploy --dir=client/dist --prod --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --site ${{ secrets.NETLIFY_SITE_ID }}
