name: CI/CD-server

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install server dependencies
        run: cd server && pnpm install
      - name: Build server
        run: cd server && pnpm run build
        env:
          PORT: ${{secrets.PORT}}
          MONGO_URL: ${{secrets.MONGO_URL}}
          JWT_TOKEN: ${{secrets.JWT_TOKEN}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: ${{secrets.AWS_REGION}}
          AWS_BUCKET_NAME: ${{secrets.AWS_BUCKET_NAME}}
      - name: Install Netlify CLI
        run: npm install -g netlify-cli
      - name: List client directory contents
        run: ls -l client
      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: "production"
